name: 'Setup C/C++'
description: 'Sets up common C/C++ problem matchers'
runs:
  using: composite
  steps:
    - run: echo "::add-matcher::gcc-matcher.json"
      shell: bash
    - run: echo "::add-matcher::msvc-matcher.json"
      shell: bash
      if: ${{ runner.os == 'Windows' }}
